@host = http://localhost:3203
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGRvbWFpbi5jb20iLCJpYXQiOjE3MDg4MDI1NTEsImV4cCI6MTcwODgwNjE1MX0.W2brgINPz4XYim9E4GikvKZ9JbQNXFf0vx2au2oAYh8


### sign in user
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "email": "user1@domain.com",
  "password": "password1"
}

### sign up user
POST {{host}}/auth/sign-up
Content-Type: application/json

{
  "email": "user1@domain.com",
  "password": "password1",
  "repeatPassword": "password1"
}


### sing out user
POST {{host}}/auth/sign-out
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1
}

### get user
GET {{host}}/users
Authorization: Bearer {{token}}

### get user by email
GET {{host}}/users?email=user1@domain.com
Authorization: Bearer {{token}}

### get user by id
GET {{host}}/users?id=1
Authorization: Bearer {{token}}


### get user by email with bad token
GET {{host}}/users?email=user1@domain
Authorization: Bearer malformed_token